schema_version = "1.0.0"

id = "spriteloom"
name = "SpriteLoom"
version = "1.0.0"
tagline = "Automate modular character sprite sheet rendering for all actions, layers, and directions"
maintainer = "billw2012"
website = "https://github.com/billw2012/SpriteLoom"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-2.0-or-later"]

wheels = []
